function mag_data = load_mag_model(inputfile)

    % Parse the given input file containing the Gaussian normalised 
    % magnetic coefficients and store the data in a single matrix.
    % 
    % Parameter
    % ---------
    %   inputfile: string 
    %       name of the input text file. This file must be generated by the 
    %       parse_igrf_spreadsheet.m function or have the same data structure.
    
    % The dg and dh values store the secular variation of the coefficients
    [deg, ord, g, dg, h, dh] = textread(inputfile, '%f %f %f %f %f %f');
    mag_data = [deg, ord, g, dg, h, dh];
    
end