function cellInfo = BUS_TEI_fun(varargin)

    % BUS_DKE returns a cell array containing bus object information
    %
    % Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
    %                 when the MATLAB file is executed.
    % The order of bus element attributes is as follows:
    %   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description

    suppressObject = false;
    if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
        suppressObject = true;
    elseif nargin > 1
        error('Invalid input argument(s) encountered');
    end

    %% Variables
    % Call Variables Needed to Define Buses
    mag_data = evalin('caller', 'env.mag_data');
    
    % Find the maximum magnetic field coefficient degree
    maxdeg = max(mag_data(:, 1));

    %% Define Bus
    cellInfo = { ...
        % TEI BUS
        { ...
        'TEI_OUT', ...
        '', ...
        '', ...
        'Auto', ...
        '-1', {...
        {'R_ecef2eci', [3, 3], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'r_sun', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'r_moon', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'tt_s', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'mag_g', [maxdeg, maxdeg+1], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'mag_h', [maxdeg, maxdeg+1], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        } ...
        } ...
        }';
    
    if ~suppressObject
        % Create bus objects in the MATLAB base workspace
        Simulink.Bus.cellToObject(cellInfo)
    end

end
