function cellInfo = BUS_SENS_PP_fun(varargin)

    % BUS_SENS_PP returns a cell array containing bus object information
    %
    % Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
    %                 when the MATLAB file is executed.
    % The order of bus element attributes is as follows:
    %   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description

    suppressObject = false;
    if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
        suppressObject = true;
    elseif nargin > 1
        error('Invalid input argument(s) encountered');
    end

    %% Variables
    % Call Variables Needed to Define Buses
    S_TIME_SENS_PP = evalin('caller', 'S_TIME_SENS_PP');

    %% Define Bus
    cellInfo = { ...
        %% INPUT

        % No BUS in INPUT - FES EXAMPLE

        %% OUTPUT
        % GYRO BUS
        { ...
        'SENS_PP_GYRO_OUT', ...
        '', ...
        '', ...
        'Auto', ...
        '-1', {...
        {'w_m_gyro', 3, 'single', S_TIME_SENS_PP.time_1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        } ...
        } ...

        % SENS PP BUS
        { ...
        'SENS_PP_MSG', ...
        '', ...
        '', ...
        'Auto', ...
        '-1', {...
        {'gyro_error', 1, 'uint8', S_TIME_SENS_PP.time_1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        } ...
        } ...
        % ADD ADDITIONAL BUS RELATED TO THE BLOCK BELOW!!!
        }';
    if ~suppressObject
        % Create bus objects in the MATLAB base workspace
        Simulink.Bus.cellToObject(cellInfo)
    end

end