function cellInfo = BUS_DKE_fun(varargin)
% BUS_DKE returns a cell array containing bus object information
%
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
%                 when the MATLAB file is executed.
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
    suppressObject = true;
elseif nargin > 1
    error('Invalid input argument(s) encountered');
end

%% Variables
% Call Variables Needed to Define Buses

%% Define Bus
cellInfo = { ...
    % DKE BUS
    { ...
    'DKE_OUT', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
    {'r', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'v', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'a', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'q', 4, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'A', [3,3], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'P', [3,3], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'w', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'wdot', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'ww', 4, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'b_i', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'sun_i', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'ecl', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'alb', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'thermal_power', 10, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'panels_power', 10, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'a_nongrav', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'d_dist', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
    } ...
    % ADD ADDITIONAL BUS RELATED TO THE BLOCK BELOW!!!
    }';
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
