function cellInfo = BUS_ACTS_PP_fun(varargin)
% BUS_ACTS_PP_fun returns a cell array containing bus object information
%
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
%                 when the MATLAB file is executed.
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
    suppressObject = true;
elseif nargin > 1
    error('Invalid input argument(s) encountered');
end

%% Variables
% Call Variables Needed to Define Buses
S_TIME_ACTS_PP=evalin('caller','S_TIME_ACTS_PP');

%% Define Bus
cellInfo = { ...
    %% INPUT
    % MTQ BUS PP IN
    { ...
    'ACTS_PP_MTQ_IN', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
    {'d_mtq', 3, 'single', S_TIME_ACTS_PP.time_1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
    } ...
    
    %% OUTPUT
    % MTQ BUS PP OUT
    { ...
    'ACTS_PP_MTQ_OUT', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
    {'i_mtq', 3, 'single', S_TIME_ACTS_PP.time_1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
    } ...
    % ADD ADDITIONAL BUS RELATED TO THE BLOCK BELOW!!!
    }';
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
