function cellInfo = BUS_NAV_fun(varargin)

    % BUS_SENS_PP returns a cell array containing bus object information
    %
    % Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
    %                 when the MATLAB file is executed.
    % The order of bus element attributes is as follows:
    %   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description

    suppressObject = false;
    if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
        suppressObject = true;
    elseif nargin > 1
        error('Invalid input argument(s) encountered');
    end

    %% Variables
    % Call Variables Needed to Define Buses
    S_TIME_NAV = evalin('caller', 'S_TIME_NAV');

    %% Define Bus
    cellInfo = { ...
        %% INPUT

        % NAV_GYRO BUS
        { ...
        'NAV_GYRO_IN', ...
        '', ...
        '', ...
        'Auto', ...
        '-1', {...
        {'w_m_gyro', 3, 'single', S_TIME_NAV.time_1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        } ...
        } ...

        % MODE MANAGER
        { ...
        'NAV_MM_IN', ...
        '', ...
        '', ...
        'Auto', ...
        '-1', {...
        {'mode', 1, 'uint16', S_TIME_NAV.time_1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        } ...
        } ...

        % Control Input
        { ...
        'NAV_CTR_IN', ...
        '', ...
        '', ...
        'Auto', ...
        '-1', {...
        {'u', 3, 'single', S_TIME_NAV.time_1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        } ...
        } ...    

        %% OUTPUT
        % Navigation Flags
        { ...
        'NAV_MSG_OUT', ...
        '', ...
        '', ...
        'Auto', ...
        '-1', {...
        {'nav_flag', 1, 'boolean', S_TIME_NAV.time_1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        } ...
        } ...
        
        % Navigation Data
        { ...
        'NAV_DATA_OUT', ...
        '', ...
        '', ...
        'Auto', ...
        '-1', {...
        {'x_est', 6, 'single', S_TIME_NAV.time_1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        } ...
        } ...
        % ADD ADDITIONAL BUS RELATED TO THE BLOCK BELOW!!!
        }';

    if ~suppressObject
        % Create bus objects in the MATLAB base workspace
        Simulink.Bus.cellToObject(cellInfo)
    end

end
