function cellInfo = BUS_CTR_fun(varargin)

    % BUS_CTR returns a cell array containing bus object information
    %
    % Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
    %                 when the MATLAB file is executed.
    % The order of bus element attributes is as follows:
    %   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description

    suppressObject = false;
    if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
        suppressObject = true;
    elseif nargin > 1
        error('Invalid input argument(s) encountered');
    end

    %% Variables
    % Call Variables Needed to Define Buses
    S_TIME_CTR = evalin('caller', 'S_TIME_CTR');

    %% Define Bus
    cellInfo = { ...
        %% INPUT
            
        % CTR_GUI_IN BUS
        { ...
        'CTR_GUI_IN', ...
        '', ...
        '', ...
        'Auto', ...
        '-1', {...
        {'uMPC', [3,1], 'single', S_TIME_CTR.time_2, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        } ...
        } ...
        
        % CTR_NAV_IN BUS
        { ...
        'CTR_NAV_IN', ...
        '', ...
        '', ...
        'Auto', ...
        '-1', {...
        {'x_est', 6, 'single', S_TIME_CTR.time_1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        } ...
        } ...
        
        % MODE MANAGER
        { ...
        'CTR_MM_IN', ...
        '', ...
        '', ...
        'Auto', ...
        '-1', {...
        {'mode', 1, 'uint16', S_TIME_CTR.time_1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'opt_1', 1, 'boolean', S_TIME_CTR.time_1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'dig_clock', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        } ...
        } ...


        %% OUTPUT
        % CTR MSG
        { ...
        'CTR_MSG_OUT', ...
        '', ...
        '', ...
        'Auto', ...
        '-1', {...
        {'ctr_flag', 1, 'uint8', S_TIME_CTR.time_1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        } ...
        } ...
        
        % CTR DATA
        { ...
        'CTR_DATA_OUT', ...
        '', ...
        '', ...
        'Auto', ...
        '-1', {...
        {'u', 3, 'single', S_TIME_CTR.time_1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        } ...
        } ...
        
        % CTR CMD
        { ...
        'CTR_CMD_OUT', ...
        '', ...
        '', ...
        'Auto', ...
        '-1', {...
        {'d_mtq', 3, 'single', S_TIME_CTR.time_1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'u', 3, 'single', S_TIME_CTR.time_1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        } ...
        } ...
        
        % ADD ADDITIONAL BUS RELATED TO THE BLOCK BELOW!!!
        }';
    if ~suppressObject
        % Create bus objects in the MATLAB base workspace
        Simulink.Bus.cellToObject(cellInfo)
    end

end